# Generated by Django 3.2.7 on 2021-09-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default=True, upload_to=''),
            preserve_default=False,
        ),
    ]
